# Generated by Django 3.1.4 on 2021-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
