# Generated by Django 3.1.4 on 2021-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumnail',
            field=models.ImageField(blank=True, default='Hello.png', null=True, upload_to=''),
        ),
    ]
