# Generated by Django 3.1.4 on 2021-07-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
